name: Express.js CD
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.USER_NAME_POSTGRES }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.USER_NAMEDB_POSTGRES }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.17"
        
      - name: Installing Dependencies
        run: npm i

      - name: testing our app
        run: npm test

  deploy:
    needs: [test]
    name: Wait for Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: call render webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_HOOK }}
          method: 'GET'
      
      # - name: Wait for Render Deployment
      #   uses: bounceapp/render-action@0.2.0
      #   with:
      #     email: vizmar.vizcaino@gmail.com
      #     password: 69720700junior
      #     token: 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
      #     service-id: srv-cdhstiha6gdsnlmm3do0